### ISSUE TITLE
PDF Issue with Acrobat Reader (cont.)

### ISSUE THREAD

**Issue by stefanDge** [manuelbl/SwissQRBill.NET#19]
[actual_a4bill_ex1.pdf](https://github.com/manuelbl/SwissQRBill.NET/files/4831886/actual_a4bill_ex1.pdf)

Thank you very much for your reply. I compiled the sources on Win 10 (1909) with VS 2019 and  and on an other machine with VS 2017 on Win 10 (1909). I tryed different .Net Versions with the same result. The software I wrote is a .Net Core 2.1 Application (VS2017) and integrates your lib with NuGet.  Version is 2.3.4 (2.3.1  produces the same result).
The file can be read from Sumatra, Firefox or Edge (Chromium) and fails with Edge (older version) and Acrobat Reader DC (current version). 
Stefan

_Originally posted by @stefanDge in https://github.com/manuelbl/SwissQRBill.NET/issues/18#issuecomment-649579531_

**Comment by manuelbl** [comment]
I was able to reproduce it. It's an invalid locale sensitivity, i.e. the media box was written as `[ 0 0 595,2756 841,8898 ]` instead of `[ 0 0 595.2756 841.8898 ]`. You are probably using a German locale with a comma in numbers (as opposed to a Swiss locale with a period).

It's fixed in release 2.3.5. PDFs have become slightly smaller as a side effect as the number of fractional digits is now limited.
